- name: Fedora basic setup
  import_tasks: fedora.yml
  when: (ansible_distribution | lower == 'fedora')

- name: Turn off event sounds
  dconf:
      key: "/org/gnome/desktop/sound/event-sounds"
      value: "false"
- name: Show date in top bar
  dconf:
      key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
- name: Set dark theme
  dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adwaita-dark'"
- name: Turn off dynamic workspaces
  dconf:
      key: "/org/gnome/mutter/dynamic-workspaces"
      value: "false"

- name: Set terminal profile name
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/visible-name"
      value: "'default'"
- name: Set terminal profile width
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-columns"
      value: "120"
- name: Set terminal profile height
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows"
      value: "36"
- name: Set terminal profile scrollbar visibility
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy"
      value: "'never'"
- name: Set terminal profile disable bell
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/audible-bell"
      value: "false"
     
- name: Set terminal profile list
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/list"
      value: "['b1dcc9dd-5262-4d8d-a863-c897e6d979b9']"
- name: Set terminal profile default
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/default"
      value: "'b1dcc9dd-5262-4d8d-a863-c897e6d979b9'"

- name: Set switch panels to something else to allow ctrl-alt-tab to be used
  dconf:
      key: "/org/gnome/desktop/wm/keybindings/switch-panels"
      value: "['<Primary><Alt>space']"
- name: Set switch panels to something else to allow ctrl-alt-tab to be used
  dconf:
      key: "/org/gnome/desktop/wm/keybindings/switch-panels-backward"
      value: "['<Primary><Shift><Alt>space']"
- name: Set ctrl-alt-tab to overview for logitech mouse
  dconf:
      key: "/org/gnome/shell/keybindings/toggle-overview"
      value: "['<Primary><Alt>Tab']"

- name: Terminal Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
      value: "'<Super>Return'"
- name: Terminal Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
      value: "'alacritty'"
- name: Terminal Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
      value: "'Launch Terminal'"
- name: Terminal Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"


- name: Disable backward scrolling
  dconf:
      key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
      value: "false"
- name: Enable tap to click
  dconf:
      key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
      value: "true"

