- name: Install Packages
  become: yes
  apt:
      name: "{{ packages }}"
      state: latest
  vars:
      packages:
      - openssh-server

- name: Enable SSH daemon
  become: yes
  systemd:
      name: ssh.service
      enabled: yes
      state: started
