- name: Fedora basic setup
  import_tasks: fedora.yml
  when: (ansible_distribution | lower == 'fedora')

- name: Enable SSH daemon
  become: yes
  systemd:
      name: sshd.service
      enabled: yes
      state: started
