- name: Fedora basic setup
  import_tasks: fedora.yml
  when: (ansible_distribution | lower == 'fedora')

- name: Turn off event sounds
  dconf:
      key: "/org/gnome/desktop/sound/event-sounds"
      value: "false"
- name: Show date in top bar
  dconf:
      key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
- name: Set dark theme
  dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adwaita-dark'"
- name: Turn off dynamic workspaces
  dconf:
      key: "/org/gnome/mutter/dynamic-workspaces"
      value: "false"
- name: Set screen blank time
  dconf:
      key: "/org/gnome/desktop/session/idle-delay"
      value: "uint32 900"

- name: Set terminal profile name
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/visible-name"
      value: "'default'"
- name: Set terminal profile width
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-columns"
      value: "120"
- name: Set terminal profile height
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows"
      value: "36"
- name: Set terminal profile scrollbar visibility
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy"
      value: "'never'"
- name: Set terminal profile disable bell
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/audible-bell"
      value: "false"
     
- name: Set terminal profile list
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/list"
      value: "['b1dcc9dd-5262-4d8d-a863-c897e6d979b9']"
- name: Set terminal profile default
  dconf:
      key: "/org/gnome/terminal/legacy/profiles:/default"
      value: "'b1dcc9dd-5262-4d8d-a863-c897e6d979b9'"

- name: Set switch panels to something else to allow ctrl-alt-tab to be used
  dconf:
      key: "/org/gnome/desktop/wm/keybindings/switch-panels"
      value: "['<Primary><Alt>space']"
- name: Set switch panels to something else to allow ctrl-alt-tab to be used
  dconf:
      key: "/org/gnome/desktop/wm/keybindings/switch-panels-backward"
      value: "['<Primary><Shift><Alt>space']"
- name: Set ctrl-alt-tab to overview for logitech mouse
  dconf:
      key: "/org/gnome/shell/keybindings/toggle-overview"
      value: "['<Primary><Alt>Tab']"

- name: Terminal Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
      value: "'<Super>Return'"
- name: Terminal Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
      value: "'tilix'"
- name: Terminal Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
      value: "'Launch Terminal'"
- name: Terminal Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"


- name: Disable backward scrolling
  dconf:
      key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
      value: "false"
- name: Enable tap to click
  dconf:
      key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
      value: "true"



##################
# Tilix          #
##################
- name: Set Tilix title style
  dconf:
      key: "/com/gexperts/Tilix/terminal-title-style"
      value: "'none'"
- name: Set Tilix profile list
  dconf:
      key: "/com/gexperts/Tilix/profiles/list"
      value: "['2b7c4080-0ddd-46c5-8f23-563fd3ba789d','f8b46731-82c2-423d-8be8-847d4ba35e7e']"
- name: Set default profile
  dconf:
      key: "/com/gexperts/Tilix/profiles/default"
      value: "'f8b46731-82c2-423d-8be8-847d4ba35e7e'"

- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/allow-bold"
      value: "true"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/automatic-switch"
      value: "@as []"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/background-color"
      value: "'#263238'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/background-transparency-percent"
      value: "0"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/backspace-binding"
      value: "'ascii-delete'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/badge-color"
      value: "'#AC7EA8'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/badge-color-set"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/badge-font"
      value: "'Monospace 12'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/badge-position"
      value: "'northeast'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/badge-text"
      value: "'${id}'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/badge-use-system-font"
      value: "true"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/bold-color"
      value: "'#ffffff'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/bold-color-set"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/bold-is-bright"
      value: "true"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/cell-height-scale"
      value: "1.0"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/cell-width-scale"
      value: "1.0"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/cjk-utf8-ambiguous-width"
      value: "'narrow'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/cursor-background-color"
      value: "'#000000'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/cursor-blink-mode"
      value: "'system'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/cursor-colors-set"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/cursor-foreground-color"
      value: "'#ffffff'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/cursor-shape"
      value: "'block'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/custom-command"
      value: "''"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/custom-hyperlinks"
      value: "@as []"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/default-size-columns"
      value: "120"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/default-size-rows"
      value: "36"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/delete-binding"
      value: "'delete-sequence'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/dim-transparency-percent"
      value: "0"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/draw-margin"
      value: "80"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/encoding"
      value: "'UTF-8'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/exit-action"
      value: "'close'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/font"
      value: "'Monospace 12'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/foreground-color"
      value: "'#A1B0B8'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/highlight-background-color"
      value: "'#000000'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/highlight-colors-set"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/highlight-foreground-color"
      value: "'#ffffff'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/login-shell"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/notify-silence-enabled"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/notify-silence-threshold"
      value: "0"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/palette"
      value: "['#000000', '#AA0000', '#00AA00', '#AA5400', '#0000AA', '#AA00AA', '#00AAAA', '#AAAAAA', '#545454', '#FF5454', '#54FF54', '#FFFF54', '#5454FF', '#FF54FF', '#54FFFF', '#FFFFFF']"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/rewrap-on-resize"
      value: "true"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/scroll-on-keystroke"
      value: "true"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/scroll-on-output"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/scrollback-lines"
      value: "8192"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/scrollback-unlimited"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/select-by-word-chars"
      value: "'-,./?%&#:_'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/shortcut"
      value: "'disabled'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/show-scrollbar"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/terminal-bell"
      value: "'none'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/terminal-title"
      value: "'${id}: ${title}'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/text-blink-mode"
      value: "'always'"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/triggers"
      value: "@as []"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/use-custom-command"
      value: "false"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/use-system-font"
      value: "true"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/use-theme-colors"
      value: "true"
- name: Set Tilix profile option
  dconf:
      key: "/com/gexperts/Tilix/profiles/f8b46731-82c2-423d-8be8-847d4ba35e7e/visible-name"
      value: "'MyProfile'"
