- name: Fedora basic setup
  import_tasks: fedora.yml
  when: (ansible_distribution | lower == 'fedora')

- name: Turn off event sounds
  dconf:
      key: "/org/gnome/desktop/sound/event-sounds"
      value: "false"
- name: Set GTK theme to Adapta
  dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adapta'"
- name: Set icon theme to Papirus-Adapta
  dconf:
      key: "/org/gnome/desktop/interface/icon-theme"
      value: "'Papirus-Adapta'"
- name: Show date in top bar
  dconf:
      key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
- name: Turn off dynamic workspaces
  dconf:
      key: "/org/gnome/mutter/dynamic-workspaces"
      value: "false"

- name: Tilix turn off title bars
  dconf:
      key: "/com/gexperts/Tilix/terminal-title-style"
      value: "'none'"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/foreground-color"
      value: "'#A1B0B8'"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/visible-name"
      value: "'Default'"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/palette"
      value: "['#252525', '#FF5252', '#C3D82C', '#FFC135', '#42A5F5', '#D81B60', '#00ACC1', '#F5F5F5', '#708284', '#FF5252', '#C3D82C', '#FFC135', '#42A5F5', '#D81B60', '#00ACC1', '#F5F5F5']"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/badge-color-set"
      value: "false"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/default-size-rows"
      value: "36"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/default-size-columns"
      value: "120"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/show-scrollbar"
      value: "false"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/cursor-colors-set"
      value: "false"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/highlight-colors-set"
      value: "false"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-theme-colors"
      value: "false"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/bold-color-set"
      value: "false"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/terminal-bell"
      value: "'none'"
- name: Tilix Profile settings
  dconf:
      key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-color"
      value: "'#263238'"
- name: Tilix Profile List
  dconf:
      key: "/com/gexperts/Tilix/profiles/list"
      value: "['2b7c4080-0ddd-46c5-8f23-563fd3ba789d']"
- name: Tilix Default Profile
  dconf:
      key: "/com/gexperts/Tilix/profiles/default"
      value: "'2b7c4080-0ddd-46c5-8f23-563fd3ba789d'"
- name: Tilix Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
      value: "'<Super>Return'"
- name: Tilix Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
      value: "'tilix'"
- name: Tilix Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
      value: "'Launch Tilix'"
- name: Tilix Add keyboard shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

- name: Set volume up shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/volume-up"
      value: "'<Alt><Super>Page_Up'"
- name: Set volume down shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/volume-down"
      value: "'<Alt><Super>Page_Down'"
- name: Set volume mute shortcut
  dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/volume-mute"
      value: "'<Alt><Super>Delete'"
