- name: Install Packages
  become: yes
  apt:
      name: "{{ packages }}"
      state: latest
  vars:
      packages:
      - build-essential
      - clang
      - clang-tools
      - cmake
      - git
      - golang
      - nodejs
      - npm
      - python3-dev
