- name: Fedora basic setup
  import_tasks: fedora.yml
  when: (ansible_distribution | lower == 'fedora')

- name: Create Vim swp folder
  file:
      path: "{{ ansible_env.HOME }}/.vim/swp"
      state: directory
- name: Create Vim autoload folder
  file:
      path: "{{ ansible_env.HOME }}/.vim/autoload"
      state: directory
- name: Download Vim Plug
  get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
- name: Install Vim Plugins
  command: vim +PlugInstall +qall
- name: Install coc.nvim requirements
  command: vim +"CocInstall coc-tsserver coc-phpls coc-html coc-css coc-json coc-go" +qall
#- name: Compile YouCompleteMe
  #command:  "{{ ansible_env.HOME }}/bin/ycm-recompile"

