- name: Fedora basic setup
  import_tasks: fedora.yml
  when: (ansible_distribution | lower == 'fedora')

- name: Create Neovim autoload folder
  file:
      path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
      state: directory
- name: Download Vim Plug
  get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
- name: Install Vim Plugins
  command: nvim --headless +PlugInstall +qall
- name: Install coc.nvim requirements
  command: 
      cmd: nvim +"CocInstall coc-tsserver coc-phpls coc-html coc-css coc-json coc-go" +qall
      chdir: "{{ ansible_env.HOME }}/.config/coc/extensions"
      cmd: npm install coc-tsserver coc-phpls coc-html coc-css coc-json coc-go coc-clangd --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
#- name: Compile YouCompleteMe
  #command:  "{{ ansible_env.HOME }}/bin/ycm-recompile"

